/**
 * Multi-set highlight store — the framework-free core of the vanilla
 * `trace_tree.html` `TraceTreeNav` pin system.
 *
 * A pin is a snapshot `{ key, slot, label, spanIds }`. Any number of sets can
 * be pinned; each takes the lowest free integer slot, and freed slots are
 * reused so a set's color stays stable across other sets' unpins. Slots 0-3
 * use the hand-tuned palette; slots >=4 are generated by the golden angle so an
 * arbitrary number of pins stay visually distinct.
 *
 * This module owns slot allocation and the pin collection only. The DOM
 * concerns it drove in the vanilla shell (stripe gutters, the legend, revealing
 * spans in the tree) move into the React components that consume `getPins()`.
 */

export const HIGHLIGHT_PALETTE = ['#ffd479', '#7fd1ff', '#b48eff', '#7fe0a3'] as const;

/** The slot's stripe color: palette for 0-3, golden-angle HSL beyond. */
export function colorForSlot(slot: number): string {
  return slot < HIGHLIGHT_PALETTE.length
    ? HIGHLIGHT_PALETTE[slot]
    : `hsl(${(slot * 137.5) % 360} 65% 65%)`;
}

/** A pinnable set: a stable key, a human label, and the spans it highlights. */
export interface PinInput {
  key: string;
  label: string;
  spanIds: readonly string[];
}

interface Pin extends PinInput {
  slot: number;
  spanIds: string[];
}

/** A read-only view of one active pin for consumers (tree stripes, flow dots). */
export interface PinView {
  key: string;
  color: string;
  label: string;
}

export class PinStore {
  private pins: Pin[] = [];

  private pinFor(key: string): Pin | undefined {
    return this.pins.find((p) => p.key === key);
  }

  isPinned(key: string): boolean {
    return this.pinFor(key) !== undefined;
  }

  slotColorFor(key: string): string | null {
    const p = this.pinFor(key);
    return p ? colorForSlot(p.slot) : null;
  }

  /** Lowest free integer slot, no upper bound. Reusing freed slots keeps a
   * set's color stable across other sets' unpins. */
  nextFreeSlot(): number {
    for (let s = 0; ; s++) {
      if (!this.pins.some((p) => p.slot === s)) return s;
    }
  }

  nextFreeColor(): string {
    return colorForSlot(this.nextFreeSlot());
  }

  /** Pin a set in the lowest free slot. Returns false (no-op) if already pinned. */
  addPin(input: PinInput): boolean {
    if (this.isPinned(input.key)) return false;
    this.pins.push({
      key: input.key,
      label: input.label,
      spanIds: input.spanIds.slice(),
      slot: this.nextFreeSlot(),
    });
    return true;
  }

  /** Remove a pin, freeing its slot. Returns false if it wasn't pinned. */
  removePin(key: string): boolean {
    const idx = this.pins.findIndex((p) => p.key === key);
    if (idx === -1) return false;
    this.pins.splice(idx, 1);
    return true;
  }

  /** Drop every pin (the tree view's Esc). */
  clearAll(): void {
    this.pins = [];
  }

  /** Active pins in slot order, each with its resolved color — for rendering. */
  getPins(): PinView[] {
    return [...this.pins]
      .sort((a, b) => a.slot - b.slot)
      .map((p) => ({ key: p.key, color: colorForSlot(p.slot), label: p.label }));
  }

  /** Whether `spanId` is one of the spans the pin `key` highlights. */
  isSpanInPin(key: string, spanId: string): boolean {
    const p = this.pinFor(key);
    return p ? p.spanIds.includes(spanId) : false;
  }

  /**
   * The stripe colors for a span: one per pinned set it belongs to, in slot
   * order (the tree draws a left-edge stripe per color). Empty when unpinned.
   */
  spanColors(spanId: string): string[] {
    return [...this.pins]
      .filter((p) => p.spanIds.includes(spanId))
      .sort((a, b) => a.slot - b.slot)
      .map((p) => colorForSlot(p.slot));
  }
}
