"""Manifest tests for the OPA policy server (issue #162).

Kept in its own module (like the workload-specific sections of
``test_manifests.py``) so the OPA deployment's expectations live next to the
issue that owns them.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

MANIFEST = Path(__file__).resolve().parents[2] / "deploy" / "k8s" / "95-opa.yaml"


@pytest.fixture(scope="module")
def docs() -> list[dict]:
    with MANIFEST.open() as fh:
        return [doc for doc in yaml.safe_load_all(fh) if doc is not None]


@pytest.fixture(scope="module")
def deployment(docs: list[dict]) -> dict:
    (dep,) = [d for d in docs if d["kind"] == "Deployment"]
    return dep


@pytest.fixture(scope="module")
def service(docs: list[dict]) -> dict:
    (svc,) = [d for d in docs if d["kind"] == "Service"]
    return svc


def test_service_named_opa_on_8181(service: dict) -> None:
    """The Service name + port make the engine's RISK_OPA_BASE_URL default
    (http://opa:8181) resolve as-is inside the namespace."""
    assert service["metadata"]["name"] == "opa"
    assert service["metadata"]["namespace"] == "data-governance"
    (port,) = service["spec"]["ports"]
    assert port["port"] == 8181


def test_opa_image_is_pinned_stock_opa(deployment: dict) -> None:
    """Issue #162: a frozen released version of stock OPA, no code changes —
    so no custom image and no :latest."""
    (container,) = deployment["spec"]["template"]["spec"]["containers"]
    image = container["image"]
    assert "openpolicyagent/opa:" in image
    assert not image.endswith(":latest")
    tag = image.rsplit(":", 1)[1]
    assert tag[0].isdigit(), f"expected a version-pinned tag, got {tag!r}"


def test_opa_loads_policies_from_configmap_mount(deployment: dict) -> None:
    """The server loads /policies (the opa-policy ConfigMap created by
    deploy/create-opa-configmap.sh from the canonical repo files) — the
    simplest load path that survives pod restarts."""
    pod = deployment["spec"]["template"]["spec"]
    (container,) = pod["containers"]
    assert container["args"][:2] == ["run", "--server"]
    assert "/policies" in container["args"]
    assert "--ignore=.*" in container["args"], (
        "kubelet's ..data symlink dir would load the bundle twice — a second "
        "`default policy_decision` is a fatal duplicate"
    )
    (mount,) = container["volumeMounts"]
    assert mount["mountPath"] == "/policies"
    (volume,) = pod["volumes"]
    assert volume["configMap"]["name"] == "opa-policy"


def test_opa_probes_target_health(deployment: dict) -> None:
    (container,) = deployment["spec"]["template"]["spec"]["containers"]
    assert container["readinessProbe"]["httpGet"]["path"] == "/health"
    assert container["livenessProbe"]["httpGet"]["path"] == "/health"


def test_configmap_is_not_embedded_in_manifests(deployment: dict) -> None:
    """The policy ConfigMap must NOT be a second, embedded copy of the repo
    files — deploy/create-opa-configmap.sh generates it from the canonical
    sources, so the manifests directory carries no drift-prone duplicate."""
    k8s_dir = MANIFEST.parent
    for path in k8s_dir.rglob("*.yaml"):
        with path.open() as fh:
            for doc in yaml.safe_load_all(fh):
                if doc and doc.get("kind") == "ConfigMap":
                    assert doc["metadata"]["name"] != "opa-policy", (
                        f"{path}: opa-policy must be generated by "
                        "deploy/create-opa-configmap.sh, not embedded"
                    )


# --- deploy/create-opa-configmap.sh -> compiled bundle ----------------------

SCRIPT = MANIFEST.parents[1] / "create-opa-configmap.sh"


def test_configmap_script_compiles_the_catalog_rather_than_copying_a_rego_file() -> None:
    """The ConfigMap is generated from the #173 compiler's output, not from a
    hand-written policy file: issue #176 made the catalog the single source
    of truth, so the script must invoke the compiler module and must not
    reference a checked-in .rego file (none exists to reference)."""
    text = SCRIPT.read_text()
    assert "python -m data_governance.risk.rules.compile" in text
    assert "rules_source.json" in text
    assert "rules/rego/" not in text
    assert '--from-file="data_governance.rego=' in text


def test_configmap_script_ships_only_the_compiled_module() -> None:
    """The compiled Rego embeds every rule's decision (``_rule_decisions``),
    so OPA needs no ``rules_source.json`` loaded as base data alongside it —
    mounting the JSON as well would be a second, unread copy."""
    text = SCRIPT.read_text()
    assert "rules_source.json=" not in text
